about/urls.py
from django.conf.urls import patterns, include, url

from about import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ntmusic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^Actors/$',views.actors, name='actors'),
    url(r'^Nadezhda/$',views.chef,{'name':'Nadezhda'}, name='Nadezhda'),
    url(r'^Tatyana/$',views.chef,{'name':'Tatyana'}, name='Tatyana'),
    url(r'^$', views.hostess, name='Hostess'),

)

afisha/urls.py
from django.conf.urls import patterns, include, url

from afisha import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ntmusic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^event/(?P<event_id>\d{1,4})/$', views.event, name='event'),
    url(r'^archives/$',views.archives, name='archives'),
    url(r'^all/$',views.all, name='all'),
    url(r'^$', views.coming, name='coming'),

)

contacts/urls.py
from django.conf.urls import patterns, include, url

from contacts import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ntmusic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.contacts, name='contacts'),
  

)

ntmusic/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ntmusic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


    #url(r'^article/', include('article.urls')),

    url(r'^afisha/', include('afisha.urls',namespace="afisha")),
    url(r'^about/',include('about.urls', namespace ="about")),
    url(r'^contacts/', include('contacts.urls',namespace="contact")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include ('top.urls', namespace="top")),


)

top/urls.py
from django.conf.urls import patterns, include, url

from top import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ntmusic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),

)

about/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models


class Actor(models.Model):
    class Meta():
        db_table = 'actor'
    name_English = models.CharField(_(u'name_English '),max_length=200)
    name = models.CharField(_(u'name '),max_length=200)
    desc = models.TextField(_(u'description'))
    title = models.TextField(_(u'title'),max_length=1000)
    chef = models.BooleanField( default = False)

    """изображение"""
    def __unicode__(self):
    	return self.name

afisha/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from datetime import datetime

class Event(models.Model):
    class Meta():
        db_table = 'event'
    name = models.CharField(_(u'name '),max_length=200)
    date = models.DateTimeField(_(u'date'))
    desc = models.TextField(_(u'description'))
    visitors = models.IntegerField(_(u'mount vizitors'),default=0)

    def __unicode__(self):
    	return self.name

guestbook/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models


class Review(models.Model):
	class Meta:
		db_table='review'
	authot = models.CharField(_(u'author'), max_length=200)
	email = models.CharField(_(u'email'), max_length=200)
	text = models.CharField(_(u'text'))
	like = models.InegerField(_(u'like'), default= 0 )
	 
# Create your models here.

about/views.py
from django.shortcuts import render , get_object_or_404
from django.http import Http404, HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
from about.models import Actor


# Create your views here.

def hostess(request):
	HOSTESS = Actor.objects.get(name_English__exact='Hostess')
	header = HOSTESS.name 
	return render_to_response('hostess.html',{'actor': HOSTESS , 'header' : header})
	

def chef(request,name):
	CHEF = Actor.objects.get(name_English__exact=name)
	header = CHEF.name
	return render_to_response('chef.html',{'actor':  CHEF , 'header': header})
    
def actors(request):
	header = " Гости музыкального салона"
	return render_to_response('actors.html',{'actors': Actor.objects.filter(chef__exact=False), 'header':header})

afisha/views.py
from django.shortcuts import render , get_object_or_404
from django.http import Http404, HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
from afisha.models import Event
from django.utils import timezone

# Create your views here.

def all(request):
    return render_to_response('all.html',{'events': Event.objects.all()})

def coming(request):
	all_events=Event.objects.filter(date__gte=timezone.now())
	events_column=[]
	for index in range(len(all_events)):
		event = []
		event.append(index%2)
		event.append(all_events[index])
		events_column.append(event)

	return render_to_response('coming.html',{'events':events_column})
	

def event(request,event_id=1):
	try:
		event_id=int(event_id)
	except ValueError:
		raise Http404()
	#сделать проверку на наличие события иначе сказать что такого нет 
	return render_to_response('event.html', {'event': Event.objects.get(id=event_id)})


def archives(request):
    return HttpResponse("hello archives")


def response(request):
	return HttpResponse("Текущая страница %s" % request.path)

contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
# Create your views here.


def contacts(request):
	return render_to_response('contacts.html')
	

guestbook/views.py
from django.shortcuts import render

# Create your views here.

top/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response
from afisha.models import Event
# Create your views here.

def index(request):
    return render_to_response('top.html')

about/templates/about.html
{%  extends 'main.html' %}
{% load staticfiles %}
{% block title %}
	Артисты музыкального салона
{% endblock %}
{% block component %}
<div class = " component">
{%include "header.html"  with header="О нас"%}


<h4> {{header}}</h4>
	{% block section %}

	{%endblock %}

</div
{% endblock %}

about/templates/actors.html
{%  extends 'about.html' %}
{% load staticfiles %}
{% block title %}
	{{ actor.title}}
{% endblock %}

{% block section %}


	{% for actor  in actors %}
	<p>{{actor.name}}</p>

	{% empty %}
		<p> Нет предстоящих событий.</p>
		<p> Появятся, когда будут.</p>
		
	{% endfor %}

{%endblock %}

about/templates/chef.html
{%  extends 'about.html' %}
{% load staticfiles %}
{% block title %}
	{{ actor.title}}
{% endblock %}

{% block section %}


<p>{{actor.desc}}</p>

{%endblock %}

about/templates/hostess.html
{%  extends 'about.html' %}
{% load staticfiles %}
{% block title %}
	{{ actor.title}}
{% endblock %}

{% block section %}


<div>
	<div class="col-sm-6 ">
		
		<a href= "{% url 'about:Nadezhda'%}"  > Надежда </a>

	</div>
	<div class="col-sm-6 ">
		
		<a href= "{% url 'about:Tatyana'%}"  > Татьяна </a>

	</div>

</div>
<div>
	{{actor.desc}}


</div>

<a href="{% url 'about:actors' %}">Гости музыкального салона</a>

{%endblock %}

afisha/templates/all.html
{%  extends 'index.html' %}
{% load staticfiles %}

{% block title %}
Афиша музыкального салона, предстоящие события
{% endblock %}
{% block section %}


	{% for event in events %}
	    <!--<a href="/afisha/event/{{ event.id}}">{{ event.event_name }}</a>-->
	    <a href="{%url 'afisha:one_event' event.id %}">{{ event.name }}</a>
	    <p>{{ event.date }}<p>
	    <p><img src="{% static "men.png" %}" width="25px" hieght="25px" > {{ event.visitors }}</p>
	    <hr>
	{% empty%}
		<p> Нет предстоящих событий</p>
	{% endfor %}

{% endblock %}

afisha/templates/coming.html
{%  extends 'index.html' %}
{% load staticfiles %}

{% block title %}
Афиша музыкального салона, предстоящие события
{% endblock %}
{% block section %}

<div>
	<div class="col-sm-6 ">
	{% for num,event in events %}
		{% if num == 0%}

		    <a href="/afisha/event/{{ event.id}}">{{ event.name }}</a>
		    <p>{{ event.date }}<p>
		    <p>Счетчик событий: {{forloop.counter}}</p>
		    
		    <p><img src="{% static "men.png" %}" width="25px" hieght="25px" > {{ event.visitors }}</p>
		    
		{% endif %}    
	{% empty %}
		<p> Нет предстоящих событий.</p>
		<p> Появятся, когда будут.</p>
		
	{% endfor %}
	</div>

	<div class="col-sm-6">

	{% for num,event in events %}
		{% if num == 1%}
		    <a href="/afisha/event/{{ event.id}}">{{ event.name }}</a>
		    <p>{{ event.date }}<p>
		    <p>Счетчик событий: {{forloop.counter}}</p>
		    <p><img src="{% static "men.png" %}" width="25px" hieght="25px" > {{ event.visitors }}</p>
		    
		 {% endif %}   	
	{% endfor %}


	</div>
</div>
{% endblock %}

afisha/templates/event.html
{%  extends 'index.html' %}
{% load staticfiles %}


{% block section %}
<h3>{{ event.name }}</h3>

<h4>{{ event.id }}</h4>
<p>{{ event.date }}</p>
{% endblock %}

afisha/templates/index.html
{%  extends 'main.html' %}
{% load staticfiles %}
{% block title %}
	Афиша музыкального салона
{% endblock %}
{% block component %}

<div class="component">

{%include "header.html"  with header="Афиша"%}

	{% block section %}

	{%endblock %}
</div>



{% endblock %}

contacts/templates/contacts.html
{%  extends 'main.html' %}
{% load staticfiles %}


{% block component %}



<div class = " component">
	{%include "header.html"  with header="Контакты"%}

	<p> nt@ntmusic.ru </p>
	

</div>

{% endblock %}

templates/header.html
<h1 class="header" style="text-align: center;"><span class="headerspan">{{header|default:"Музыкальный салон"}}</span></h1>
<p style="text-align: center;"> </p>

templates/main.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} Музыкальный салон "У Н. и Т." | ntmusic.ru {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css "%}" >
        <link rel="stylesheet" type="text/css" href="{% static "css/template.css "%}" >
        <link rel="stylesheet" type="text/css" href="{% static "css/leftside.css "%}" >

        <meta name="description" content="Добро пожаловать в наш Музыкальный салон - мир старинного, классического и современного романса и камерной музыки">
        <meta name="keywords" content=" Надежда , Татьяна ,  музыкальный салон , романс , музыка , вокал , камерная музыка , концерт , тематический концерт , музыкальная гостиная , дед мороз , снегурочка">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>

    </head>
    <body>
    <div>
        <div class="row  page "  >

            <div class=" col-sm-3 left_side">
                <div class="  logo">
                    <a href="/">
                        <img src={% static "image/logo_ntmusic.png"%} alt= " Музыкальный салон ">
                    </a>    
                </div>
                {% include "nav.html" %}
                
                <div class=" vignette">
                    <img src={% static "image/vignette.png"%}>
                </div>
                <div class="">
                    <div class="col-sm-4 out_link">
                        <a href="http://vk.com/ntmuzsalon"><img src={% static "image/iconVk.png" %} alt="Мы Вконтакте" class="soc_link_img"></a>
                    </div>
                    <div class="col-sm-4 out_link">
                        <a href="https://www.facebook.com/groups/ntmusic/?notif_t=group_added_to_group"><img src={% static "image/iconFacebook.png"%} alt="Мы в Facebook" class="soc_link_img"></a>
                    </div>
                    <div class="col-sm-4 out_link">
                        <a href="http://www.youtube.com/channel/UCPvEmGOp_DTvR8UW0heZj4w"><img src={% static "image/iconYoutube.png"%} alt="Мы на YouTube" class="soc_link_img"></a>
                    </div>
                    
                </div>
                <div class="">
                    <p class ="authors">Фотограф:<span style="text-decoration: underline;"><a href="http://peterchumakov.wix.com/peterchumakov">&nbsp;Петр Чумаков</a></span></p>
                    <p class="authors">Дизайн сайта: Ксения Неродо</p>
                </div>
                <div class="">
                    <p><i class="copyright">Copyright ntmusic.ru 2014 © </i></p>
                </div>  


            </div>
            <div class="col-sm-9 right_side">
                {% block component  %}

                {% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>

templates/nav.html
<div class=" topMenu">
    <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'top:index' %}">Главная</a></li>    
        <li><a href="{% url 'about:Hostess' %}">O нас</a></li>    
        <li><a href="{% url 'afisha:coming' %}">Афиша</a></li> 
        <li><a href="{% url 'top:index' %}">Наши предложения</a></li>    
        <li><a href="{% url 'top:index' %}">Почитать</a></li>    
        <li><a href="{% url 'top:index' %}">Послушать и посмотреть</a></li>    
        <li><a href="{% url 'top:index' %}">Наши партнеры</a></li>    
        <li><a href="{% url 'top:index' %}">Гостевая книга</a></li>    
        <li><a href="{% url 'contact:contacts' %}">Контакты</a></li>       
    </ul>         
</div>

top/templates/top.html
{%  extends 'main.html' %}
{% load staticfiles %}


{% block component %}

<div >

	<img src="{% static "image/foto_home.jpg" %}" >

</div>

{% endblock %}